<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.4" xml:lang="en-US">
  <compounddef id="classutils_1_1GitRepoNotFoundError" kind="class" language="Python" prot="public">
    <compoundname>utils::GitRepoNotFoundError</compoundname>
    <basecompoundref refid="classException" prot="public" virt="non-virtual">Exception</basecompoundref>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="2">
        <label>Exception</label>
        <link refid="classException"/>
      </node>
      <node id="1">
        <label>utils.GitRepoNotFoundError</label>
        <link refid="classutils_1_1GitRepoNotFoundError"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2">
        <label>Exception</label>
        <link refid="classException"/>
      </node>
      <node id="1">
        <label>utils.GitRepoNotFoundError</label>
        <link refid="classutils_1_1GitRepoNotFoundError"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="/tmp/github_repos_arch_doc_gen/SingularityX-ai/penify-cli/penify_hook/utils.py" line="3" column="1" bodyfile="/tmp/github_repos_arch_doc_gen/SingularityX-ai/penify-cli/penify_hook/utils.py" bodystart="3" bodyend="5"/>
    <listofallmembers>
    </listofallmembers>
  </compounddef>
</doxygen>
