<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<section xmlns="http://docbook.org/ns/docbook" version="5.0" xmlns:xlink="http://www.w3.org/1999/xlink" xml:id="_classException" xml:lang="en-US">
<title>Exception Class Reference</title>
<indexterm><primary>Exception</primary></indexterm>
Inheritance diagram for Exception:<para>
    <informalfigure>
        <mediaobject>
            <imageobject>
                <imagedata width="50%" align="center" valign="middle" scalefit="0" fileref="classException__inherit__graph.svg"></imagedata>
            </imageobject>
        </mediaobject>
    </informalfigure>
</para>
Collaboration diagram for Exception:<para>
    <informalfigure>
        <mediaobject>
            <imageobject>
                <imagedata width="50%" align="center" valign="middle" scalefit="0" fileref="classException__coll__graph.svg"></imagedata>
            </imageobject>
        </mediaobject>
    </informalfigure>
</para>
<para>
The documentation for this class was generated from the following file:</para>
/tmp/github_repos_arch_doc_gen/SingularityX-ai/penify-cli/penify_hook/<link linkend="_utils_8py">utils.py</link></section>
